apiVersion: v1
kind: Service
metadata:
  name: github-webhook-receiver-service
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    # Pods with labels matching this key/value pair will be publically
    # accessible through the service IP and port.
    run: github-webhook-receiver
  sessionAffinity: None
  type: LoadBalancer
